export enum ErrorCode {
  // Auth errors
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_CPF = 'INVALID_CPF',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PHONE = 'INVALID_PHONE',

  // User errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  CPF_ALREADY_IN_USE = 'CPF_ALREADY_IN_USE',

  // Account errors
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',

  // Pix errors
  PIX_KEY_NOT_FOUND = 'PIX_KEY_NOT_FOUND',
  PIX_KEY_ALREADY_EXISTS = 'PIX_KEY_ALREADY_EXISTS',
  PIX_KEY_LIMIT_REACHED = 'PIX_KEY_LIMIT_REACHED',
  PIX_SELF_TRANSFER = 'PIX_SELF_TRANSFER',
  PIX_INVALID_AMOUNT = 'PIX_INVALID_AMOUNT',

  // Business rules
  DAILY_LIMIT_EXCEEDED = 'DAILY_LIMIT_EXCEEDED',
  NIGHT_LIMIT_EXCEEDED = 'NIGHT_LIMIT_EXCEEDED',
  REINFORCED_AUTH_REQUIRED = 'REINFORCED_AUTH_REQUIRED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Card errors
  CARD_NOT_FOUND = 'CARD_NOT_FOUND',
  CARD_BLOCKED = 'CARD_BLOCKED',
  CARD_LIMIT_EXCEEDED = 'CARD_LIMIT_EXCEEDED',
  CARD_INACTIVE = 'CARD_INACTIVE',

  // Payment errors
  BOLETO_INVALID = 'BOLETO_INVALID',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_PAID = 'PAYMENT_ALREADY_PAID',

  // Chat errors
  CHAT_CONVERSATION_NOT_FOUND = 'CHAT_CONVERSATION_NOT_FOUND',
  CHAT_MESSAGE_TOO_LONG = 'CHAT_MESSAGE_TOO_LONG',
  CHAT_RATE_LIMITED = 'CHAT_RATE_LIMITED',
  CHAT_AI_ERROR = 'CHAT_AI_ERROR',
  CHAT_TRANSACTION_NOT_CONFIRMED = 'CHAT_TRANSACTION_NOT_CONFIRMED',

  // Generic
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  FORBIDDEN = 'FORBIDDEN',
}
